## This is kubernetes version 1.21
apiVersion: apps/v1
kind: Deploymeny
metadata:
  name: simple-python-app
  labels:
    app: pythonapp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: pythonapp
    template:
      metadata:
        labels:
          app: pythonapp
      spec:
        containers:
        - name: hello-world
          image: klinz01/pythonapp:latest
          ports:
          - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  selector:
    app: pyhtonapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31230
